In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)




[1 2 3 4 5]


In [8]:
import numpy as np
arr = np.array(42)

print(arr)

42


In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [17]:
import numpy as np

a = np.array([8])
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
1
2
3


numpy 


In [28]:
import numpy as np
b = [[1,2,3],[4,5,6,],[7,8,9,],[10,11,12]]
e = np.array(b)


In [29]:
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
e[0,0],e[1,1],e[2,2]

(1, 5, 9)

In [56]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],
              [[19,20,21],[22,23,24],[25,26,27]]])
print(w, '\n')
print('the shape of w is', w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 

the shape of w is (3, 3, 3)


In [54]:
w[0,0,2]

3

In [61]:
w[1,0,2],w[1,1,1],w[1,2,0]

(12, 14, 16)

In [65]:
w[2,0,0],w[2,1,1],w[2,2,2]

(19, 23, 27)

In [53]:
w

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [69]:
a12 = np.arange(20)
print(a12)
print(a12.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [75]:
b12 = a12.reshape(4,5)

In [76]:
b12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
b12 = a12.reshape(2,10)

In [79]:
b12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [94]:
np_zeros = np.zeros((3,3))

In [95]:
np_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np_ones = np.ones((2,3))

In [90]:
np_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [100]:
np_full = np.full((3,3), 1)

In [101]:
np_full

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [104]:
np_eye = np.eye(5,8)

In [105]:
np_eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [110]:
np_linspace = np.linspace(1,15, num=8)

In [111]:
np_linspace

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

In [119]:
np_rand = np.random.random((2,3))
print(np_rand)

[[0.00907323 0.38760452 0.57696768]
 [0.46206204 0.87829487 0.70170363]]


In [113]:
print(np_rand)

[[0.08897662 0.59228169 0.11245427]
 [0.67198468 0.09538881 0.58565491]]


In [125]:
w[0,2,2]=18

In [126]:
w

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 18]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [127]:
w[1,2,2]=28

In [128]:
w

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 18]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 28]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [129]:
w[2,2,2]= 38

In [130]:
w

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 18]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 28]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 38]]])

In [150]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [158]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [159]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [160]:
a[0:3,2:3]

array([[ 3],
       [ 7],
       [11]])